[package]
authors = ["Cleber de Moraes Goncalves <cleber.engineer@hotmail.com>"]
description = "Simples, peque e imperfeito. Uma visão além da programação"
edition = "2018"
license = "MIT"
name = "kuba"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
