[package]
authors = ["Cleber de Moraes Goncalves <cleber.engineer@gmail.com>"]
edition = "2021"
license = "MIT"
name = "kuba"
version = "0.1.0"

[workspace]
members = [
  "standard"
]

[dependencies]
standard = { path = "standard" }
