[package]
name = "kuba"
version = "0.1.1"
authors = ["Cleber de Moraes Goncalves <cleber.engineer@hotmail.com>"]
edition = "2018"
description = "Simples, peque e imperfeito. Uma visão além da programação"
documentation = "https://github.com/deMGoncalves/kuba/wiki"
readme = "README.md"
homepage = "https://kuba.engineer"
repository = "https://github.com/deMGoncalves/kuba"
license = "MIT"
keywords = ["web", "webassembly"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasm-bindgen = "0.2"

[dev-dependencies]
wasm-bindgen-test = "0.2"
