[package]
name = "kuba"
version = "0.1.0"
authors = ["Cleber de Moraes Goncalves <cleber.engineer@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
